name:Sonarscannerdotnet
  uses:dotnet-sonarscanner@v2.2
  with:
    buildCommand:dotnet build 
    projectKey:a-project-key
    projectName:'projectname'
    sonarOrganisation: an-org
    beginArguments: >
        /d:sonar.verbose="true"
        /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
        /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}